name: MacOS build and test rolesanywhere-credential-helper
on:
  workflow_dispatch:
  push:
    branches: [ main, feature/upgrade-to-golang-1.24.11 ]

permissions:
  statuses: write
  id-token: write

jobs:
  OSX:
    name: Build on ${{matrix.runner_image}}
    runs-on: ${{matrix.runner_image}}
    strategy:
      matrix:
        include:
          - runner_image: macos-15-intel
            arch: "X86_64"
            display_name: "MacOS X86_64"
          - runner_image: macos-14
            arch: "Aarch64"
            display_name: "MacOS Aarch64"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true


      - name: Set Environment Variables for Sonoma Compatability in x86
        run: |
          if [[ "${{ matrix.arch }}" == "X86_64" ]]; then
            export MACOSX_DEPLOYMENT_TARGET="14.0"
            export CGO_CFLAGS="-mmacosx-version-min=14.0" 
            export CGO_LDFLAGS="-mmacosx-version-min=14.0"
            
            echo $MACOSX_DEPLOYMENT_TARGET
            echo $CGO_CFLAGS
            echo $CGO_LDFLAGS
          fi

      - name: Build Project
        run: |
          echo $MACOSX_DEPLOYMENT_TARGET
          echo $CGO_CFLAGS
          echo $CGO_LDFLAGS
          echo "Building on ${{ matrix.display_name }}"
          make release
          make test
          otool -l build/bin/aws_signing_helper

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: aws_signing_helper
          path: build/bin/aws_signing_helper
          retention-days: 1